# Don't change this
version: 1
# bStats metrics
metrics: true

replace:
  # Replace buried treasure maps in vanilla chest loot tables
  chests: true
  villagers:
    # Replace monument map offers from villagers
    monument: true
    # Replace mansion map offers from villagers
    mansion: false

# Configure messages for the plugin
messages:
  # Configure messages relating to the map
  map:
    # Configure the lore added to maps that can be used to get the treasure
    use:
      - <green>Use to receive treasure!
