[versions]
minecraft = "1.21"
junit = "5.9.1"
mirror = "0.2.0"
reflectionRemapper = "0.1.1"

paperweight = "1.7.1"
runPaper = "2.3.0"
shadow = "8.1.7"
spotless = "6.17.0"

[libraries]
junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
mirror = { module = "me.machinemaker.mirror:mirror-paper", version.ref = "mirror" }
reflectionRemapper = { module = "xyz.jpenilla:reflection-remapper", version.ref = "reflectionRemapper" }

[plugins]
paper-userdev = { id = "io.papermc.paperweight.userdev", version.ref = "paperweight" }
paper-run = { id = "xyz.jpenilla.run-paper", version.ref = "runPaper" }
shadow = { id = "io.github.goooler.shadow", version.ref = "shadow" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
